#!/system/bin/sh
# profiles/balanced.sh — values + apply calls for the Balanced profile.
# Sourced by dispatcher after detect; calls each apply_* in fixed order.

CPU_CORE_CTL=1
CPU_BOOST_MS=
CPU_BOOST_FREQ=
CPU_IBOOST_DUR=
CPU_IBOOST_FREQ=
CPU_MIN_FREQ=100000
CPU_MAX_FREQ=$CPU_MAXFREQ
CPU_DEEPEST=1
CPU_SU_UP=4000
CPU_SU_DOWN=16000
CPU_SU_PL=0
CPU_SU_IOWAIT=0
CPU_SU_RATE=16000
CPU_SU_HISPEED_LOAD=89
CPU_SU_HISPEED_FREQ=$CPU_MAXFREQ
CPU_INT_TIMER_RATE=40000
CPU_INT_BOOST=0
CPU_INT_TIMER_SLACK=40000
CPU_INT_MIGRATION=1
CPU_INT_IGNORE_HISPEED=1
CPU_INT_SCHED_LOAD=1
CPU_INT_BOOSTPULSE=0
CPU_INT_FASTLANE=1
CPU_INT_FAST_RAMP_DOWN=0
CPU_INT_SAMPLING=40000
CPU_INT_SAMPLING_MIN=50000
CPU_INT_MIN_SAMPLE=50000
CPU_INT_GO_HISPEED=89
CPU_INT_HISPEED_FREQ=$CPU_MAXFREQ

GPU_THROTTLE=1
GPU_PWRLEVEL=0
GPU_ADRENOBOOST=0
GPU_NONAP=0
GPU_BUS_SPLIT=1
GPU_MAX_FREQ_SET=$GPU_MAXFREQ
GPU_MIN_FREQ_SET=100000000
GPU_DEF_PWRLEVEL=$GPU_MINPL
GPU_FORCE_BUS=0
GPU_FORCE_CLK=0
GPU_FORCE_RAIL=0
GPU_IDLE_TIMER=96
GPU_THERMAL_IGNORE=0
GPU_IDLER=Y
GPU_IDLER_WORKLOAD=6000
GPU_IDLER_DOWNDIFF=25
GPU_IDLER_IDLEWAIT=25

IO_ADD_RANDOM=0
IO_IOSTATS=0
IO_READ_AHEAD=128
IO_NOMERGES=2
IO_RQ_AFFINITY=1
IO_NR_REQUESTS=64

SCHED_FEATURES="NEXT_BUDDY TTWU_QUEUE NO_GENTLE_FAIR_SLEEPERS WAKEUP_PREEMPTION"
SCHED_CHILD_FIRST=0
SCHED_BOOST=0
SCHED_PERF_PCT=15
SCHED_AUTOGROUP=1
SCHED_RAND_READ=64
SCHED_RAND_WRITE=256
SCHED_RESEED=90
SCHED_TUNABLE_SCALING=0
SCHED_LATENCY=4000000
SCHED_MIN_GRAN=500000
SCHED_WAKEUP_GRAN=2000000
SCHED_MIGRATION_COST=5000000
SCHED_COLOCATION=0
SCHED_NR_MIGRATE=32
SCHED_STATS=0
SCHED_SYNC_HINT=0
SCHED_USER_HINT=0
SCHED_CONSERVATIVE_PL=
SCHED_GENTLE=1

STUNE_BG_BOOST=0
STUNE_BG_IDLE=0
STUNE_FG_BOOST=0
STUNE_FG_IDLE=1
STUNE_RT_BOOST=0
STUNE_RT_IDLE=0
STUNE_TOP_BOOST=10
STUNE_TOP_IDLE=1
STUNE_BOOST=0
STUNE_IDLE=0

MSM_VDD=0
MSM_CORE=1
MSM_ENABLED=Y
WQ_EFFICIENT=Y
SCHED_MC=1

VM_DROP_WRITE=3
VM_DIRTY_BG=10
VM_DIRTY_RATIO=30
VM_DIRTY_EXPIRE=1000
VM_DIRTY_WRITEBACK=3000
VM_PAGE_CLUSTER=0
VM_STAT_INTERVAL=60
VM_SWAPPINESS=100
VM_LAPTOP_MODE=0
VM_VFS_PRESSURE=50

TOUCHBOOST=0
BATTERY_SAVER=
ARCH_POWER=
PM2_IDLE=Y
LCD_POWER=0
KSM_RUN=1
MPDECISION=start

apply_renice
apply_cpu
apply_gpu
apply_io
apply_sched
apply_stune
apply_thermal
apply_vm
apply_fs
apply_display
apply_ksm
