#!/system/bin/sh
# profiles/battery.sh — values + apply calls for the Battery profile.
# Sourced by dispatcher after detect; calls each apply_* in fixed order.
# Dead legacy branches (unset $percentage core-offline) intentionally omitted.

CPU_CORE_CTL=1
CPU_BOOST_MS=0
CPU_BOOST_FREQ=
CPU_IBOOST_DUR=0
CPU_IBOOST_FREQ=
CPU_MIN_FREQ=100000
CPU_MAX_FREQ=$CPU_HALF
CPU_DEEPEST=1
CPU_SU_UP=8000
CPU_SU_DOWN=32000
CPU_SU_PL=0
CPU_SU_IOWAIT=0
CPU_SU_RATE=32000
CPU_SU_HISPEED_LOAD=99
CPU_SU_HISPEED_FREQ=$CPU_HALF
CPU_INT_TIMER_RATE=50000
CPU_INT_BOOST=0
CPU_INT_TIMER_SLACK=50000
CPU_INT_MIGRATION=1
CPU_INT_IGNORE_HISPEED=1
CPU_INT_SCHED_LOAD=1
CPU_INT_BOOSTPULSE=0
CPU_INT_FASTLANE=1
CPU_INT_FAST_RAMP_DOWN=1
CPU_INT_SAMPLING=50000
CPU_INT_SAMPLING_MIN=75000
CPU_INT_MIN_SAMPLE=75000
CPU_INT_GO_HISPEED=99
CPU_INT_HISPEED_FREQ=$CPU_HALF

GPU_THROTTLE=1
GPU_PWRLEVEL=0
GPU_ADRENOBOOST=0
GPU_NONAP=0
GPU_BUS_SPLIT=1
GPU_MAX_FREQ_SET=$GPU_HALF
GPU_MIN_FREQ_SET=100000000
GPU_DEF_PWRLEVEL=$GPU_MINPL
GPU_FORCE_BUS=0
GPU_FORCE_CLK=0
GPU_FORCE_RAIL=0
GPU_IDLE_TIMER=36
GPU_THERMAL_IGNORE=0
GPU_IDLER=Y
GPU_IDLER_WORKLOAD=10000
GPU_IDLER_DOWNDIFF=35
GPU_IDLER_IDLEWAIT=15

IO_ADD_RANDOM=0
IO_IOSTATS=0
IO_READ_AHEAD=128
IO_NOMERGES=0
IO_RQ_AFFINITY=0
IO_NR_REQUESTS=64

SCHED_FEATURES="NEXT_BUDDY TTWU_QUEUE NO_WAKEUP_PREEMPTION NO_GENTLE_FAIR_SLEEPERS ARCH_POWER"
SCHED_CHILD_FIRST=1
SCHED_BOOST=0
SCHED_PERF_PCT=10
SCHED_AUTOGROUP=1
SCHED_RAND_READ=64
SCHED_RAND_WRITE=128
SCHED_RESEED=90
SCHED_TUNABLE_SCALING=0
SCHED_LATENCY=8000000
SCHED_MIN_GRAN=2000000
SCHED_WAKEUP_GRAN=4000000
SCHED_MIGRATION_COST=5000000
SCHED_COLOCATION=0
SCHED_NR_MIGRATE=8
SCHED_STATS=0
SCHED_SYNC_HINT=0
SCHED_USER_HINT=0
SCHED_CONSERVATIVE_PL=
SCHED_GENTLE=0

STUNE_BG_BOOST=0
STUNE_BG_IDLE=0
STUNE_FG_BOOST=0
STUNE_FG_IDLE=1
STUNE_RT_BOOST=0
STUNE_RT_IDLE=0
STUNE_TOP_BOOST=5
STUNE_TOP_IDLE=1
STUNE_BOOST=0
STUNE_IDLE=0

MSM_VDD=1
MSM_CORE=1
MSM_ENABLED=Y
WQ_EFFICIENT=Y
SCHED_MC=2

VM_DROP_WRITE=
VM_DIRTY_BG=5
VM_DIRTY_RATIO=50
VM_DIRTY_EXPIRE=3000
VM_DIRTY_WRITEBACK=3000
VM_PAGE_CLUSTER=0
VM_STAT_INTERVAL=60
VM_SWAPPINESS=100
VM_LAPTOP_MODE=0
VM_VFS_PRESSURE=50

TOUCHBOOST=0
BATTERY_SAVER=Y
ARCH_POWER=
PM2_IDLE=
LCD_POWER=1
KSM_RUN=0
MPDECISION=start

apply_renice
apply_cpu
apply_gpu
apply_io
apply_sched
apply_stune
apply_thermal
apply_vm
apply_fs
apply_display
apply_ksm
