#!/system/bin/sh
# profiles/gaming.sh — values + apply calls for the Gaming profile.
# Sourced by dispatcher after detect; calls each apply_* in fixed order.

CPU_CORE_CTL=
CPU_BOOST_MS=128
CPU_BOOST_FREQ="0:$CPU_MAXFREQ 1:$CPU_MAXFREQ 2:$CPU_MAXFREQ 3:$CPU_MAXFREQ 4:$CPU_MAXFREQ 5:$CPU_MAXFREQ 6:$CPU_MAXFREQ 7:$CPU_MAXFREQ"
CPU_IBOOST_DUR=128
CPU_IBOOST_FREQ=$CPU_MAXFREQ
CPU_MIN_FREQ=$CPU_MAXFREQ
CPU_MAX_FREQ=$CPU_MAXFREQ
CPU_DEEPEST=0
CPU_SU_UP=500
CPU_SU_DOWN=20000
CPU_SU_PL=1
CPU_SU_IOWAIT=1
CPU_SU_RATE=20000
CPU_SU_HISPEED_LOAD=80
CPU_SU_HISPEED_FREQ=4294967295
CPU_INT_TIMER_RATE=20000
CPU_INT_BOOST=1
CPU_INT_TIMER_SLACK=20000
CPU_INT_MIGRATION=1
CPU_INT_IGNORE_HISPEED=1
CPU_INT_SCHED_LOAD=1
CPU_INT_BOOSTPULSE=0
CPU_INT_FASTLANE=1
CPU_INT_FAST_RAMP_DOWN=0
CPU_INT_SAMPLING=20000
CPU_INT_SAMPLING_MIN=20000
CPU_INT_MIN_SAMPLE=20000
CPU_INT_GO_HISPEED=80
CPU_INT_HISPEED_FREQ=4294967295

GPU_THROTTLE=0
GPU_PWRLEVEL=0
GPU_ADRENOBOOST=2
GPU_NONAP=1
GPU_BUS_SPLIT=0
GPU_MAX_FREQ_SET=$GPU_MAXFREQ
GPU_MIN_FREQ_SET=$GPU_TOPMIN_FREQ
GPU_DEF_PWRLEVEL=$(cat "$GPU_DIR/max_pwrlevel" 2>/dev/null)
GPU_FORCE_BUS=1
GPU_FORCE_CLK=1
GPU_FORCE_RAIL=1
GPU_IDLE_TIMER=1050
GPU_THERMAL_IGNORE=1
GPU_IDLER=N
GPU_IDLER_WORKLOAD=
GPU_IDLER_DOWNDIFF=
GPU_IDLER_IDLEWAIT=

IO_ADD_RANDOM=0
IO_IOSTATS=0
IO_READ_AHEAD=512
IO_NOMERGES=2
IO_RQ_AFFINITY=2
IO_NR_REQUESTS=256

SCHED_FEATURES="NEXT_BUDDY TTWU_QUEUE NO_GENTLE_FAIR_SLEEPERS NO_WAKEUP_PREEMPTION"
SCHED_CHILD_FIRST=0
SCHED_BOOST=1
SCHED_PERF_PCT=25
SCHED_AUTOGROUP=1
SCHED_RAND_READ=128
SCHED_RAND_WRITE=1024
SCHED_RESEED=90
SCHED_TUNABLE_SCALING=0
SCHED_LATENCY=10000000
SCHED_MIN_GRAN=1666666
SCHED_WAKEUP_GRAN=5000000
SCHED_MIGRATION_COST=5000000
SCHED_COLOCATION=0
SCHED_NR_MIGRATE=128
SCHED_STATS=0
SCHED_SYNC_HINT=0
SCHED_USER_HINT=0
SCHED_CONSERVATIVE_PL=0
SCHED_GENTLE=0

STUNE_BG_BOOST=0
STUNE_BG_IDLE=0
STUNE_FG_BOOST=50
STUNE_FG_IDLE=0
STUNE_RT_BOOST=0
STUNE_RT_IDLE=0
STUNE_TOP_BOOST=50
STUNE_TOP_IDLE=0
STUNE_BOOST=0
STUNE_IDLE=0

MSM_VDD=0
MSM_CORE=0
MSM_ENABLED=N
WQ_EFFICIENT=N
SCHED_MC=0

VM_DROP_WRITE=3
VM_DIRTY_BG=5
VM_DIRTY_RATIO=20
VM_DIRTY_EXPIRE=500
VM_DIRTY_WRITEBACK=3000
VM_PAGE_CLUSTER=0
VM_STAT_INTERVAL=60
VM_SWAPPINESS=100
VM_LAPTOP_MODE=0
VM_VFS_PRESSURE=200

TOUCHBOOST=1
BATTERY_SAVER=N
ARCH_POWER=0
PM2_IDLE=N
LCD_POWER=0
KSM_RUN=1
MPDECISION=stop

apply_renice
apply_cpu
apply_gpu
apply_io
apply_sched
apply_stune
apply_thermal
apply_vm
apply_fs
apply_display
apply_ksm
